version: '3'
services:
  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
    ports:
      - 9080:9080