apiVersion: apps/v1
kind: Deployment
metadata:
  name: trace-test-api-deployment
  namespace: playground
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trace-test-api
  template:
    metadata:
      labels:
        app: trace-test-api
    spec:
      containers:
        - name: test-api-service
          image: harbor.e4r.internal/canfar/test-trace:latest
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: trace-test-api-service
  namespace: playground
spec:
  selector:
    app: trace-test-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP